#!/usr/bin/env python3
"""Emit the Chronos/M4-Monthly tables from that arm's own records. No flags, on purpose.

TWO FILES, because the appendix has two separate things to show and merging them would hide one:

  paper_8/tables/chronos_m4_gate.tex   the value gate's full rung ladder on BOTH splits, with the
                                       `constant` admissibility floor marked. The point of the table
                                       is not the primary number alone; it is that the superseded
                                       `trend` denominator -- the one that produced the 84.5% this
                                       appendix used to quote -- is INADMISSIBLE on the split the
                                       protocol scores, being worse than a training-mean predictor.
  paper_8/tables/chronos_m4.tex        the six runs: per-seed held-out forgetting under B and D,
                                       their paired difference, CKA and encoder l2 drift.

NO FLAGS. scripts/rederive_all.sh has twice contained an emitter invoked without its emit flag,
printing "ok" for ten rounds while the table it was supposed to write went stale. A script with one
behaviour cannot be invoked in the wrong mode.

PROVISIONAL. If any registered (condition, seed) record is missing, both tables are still written and
carry a visible in-PDF marker, and this script says so on stdout. A silently short table is the
failure mode that made this arm necessary in the first place.

Run:  .venv12/bin/python scripts/emit_chronos_m4.py
"""
import json
import sys
from pathlib import Path

import numpy as np
from scipy import stats

ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / "results/chronos_m4"
OUT_RUNS = ROOT / "paper_8/tables/chronos_m4.tex"
OUT_GATE = ROOT / "paper_8/tables/chronos_m4_gate.tex"

# Rung display names and the order the ladder is read in: the superseded denominator first, the
# paper's primary second, then the eight-rung ladder from weakest to strongest.
RUNG_LABEL = {
    "trend": r"trend (superseded)", "fitted": r"fitted ridge \textbf{(primary)}",
    "constant": r"constant (floor)", "persistence": "persistence",
    "seasonal_naive": "seasonal naive", "ar": "AR", "dlinear": "DLinear",
    "ridge_tuned": "ridge, tuned", "mlp": "MLP", "gbm": "GBM",
}
ORDER = ["trend", "fitted", "constant", "persistence", "seasonal_naive", "ar", "dlinear",
         "ridge_tuned", "mlp", "gbm"]


def load():
    gate = json.load(open(RES / "gate.json"))
    reg = json.load(open(RES / "preregistration.json"))
    runs, missing = {}, []
    for cond in reg["runs"]["conditions"]:
        for seed in reg["runs"]["seeds"]:
            p = RES / f"cond_{cond}" / f"seed{seed}" / f"condition_{cond}_s{seed}.json"
            if p.exists():
                runs[(cond, seed)] = json.load(open(p))
            else:
                missing.append((cond, seed))
    return gate, reg, runs, missing


def gate_table(gate):
    L = ["% GENERATED by scripts/emit_chronos_m4.py -- do not edit by hand.",
         r"\begin{center}", r"\small", r"\setlength{\tabcolsep}{5pt}",
         r"\begin{tabular}{@{}lccccc@{}}", r"\toprule",
         r"& \multicolumn{2}{c}{Selection split (primary)} & "
         r"\multicolumn{2}{c}{Held-out split} & \\",
         r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}",
         r"Denominator & MSE & $\Vb{b}$ & MSE & $\Vb{b}$ & Admissible \\",
         r"\midrule"]
    sel, ho = gate["splits"]["selection"], gate["splits"]["heldout"]
    assert not sel["rungs"]["trend"]["admissible"], (
        "the superseded trend denominator is admissible on the selection split -- the appendix text "
        "asserts it is not, so one of the two is now wrong")
    for name in ORDER:
        s, h = sel["rungs"][name], ho["rungs"][name]
        # Admissibility is a property of the split, and this cell is the one where the two disagree:
        # `trend` is worse than the constant floor on the selection windows and better than it on the
        # held-out ones. One column cannot say that, so the column reports the SELECTION split -- the
        # split every admission decision is made on -- and the note says where they differ.
        mark = {True: r"\checkmark", False: r"---"}[s["admissible"]]
        if name == "constant":
            mark = r"floor"
        L.append(f"{RUNG_LABEL[name]} & ${s['baseline_mse']:.3f}$ & ${s['r2_task']:+.3f}$ & "
                 f"${h['baseline_mse']:.3f}$ & ${h['r2_task']:+.3f}$ & {mark} \\\\")
        if name == "fitted":
            L.append(r"\midrule")
    L += [r"\bottomrule", r"\end{tabular}"]
    # Two facts a reader would otherwise have to reconstruct from the numbers, both generated rather
    # than typed so they cannot drift from the table above them.
    flips = [n for n in ORDER
             if sel["rungs"][n]["admissible"] != ho["rungs"][n]["admissible"] and n != "constant"]
    if flips:
        L.append(r"\\[2pt]\footnotesize The admissibility column is the \emph{selection} split, the "
                 "split every admission decision is made on. " +
                 ", ".join(RUNG_LABEL[n] for n in flips) +
                 (" is" if len(flips) == 1 else " are") +
                 " admissible on the held-out split and not on the selection split, "
                 f"the constant floor being ${ho['constant_floor_mse']:.3f}$ there against "
                 f"${sel['constant_floor_mse']:.3f}$ here.")
    tied = [n for n in ("ar", "dlinear", "ridge_tuned")
            if abs(sel["rungs"][n]["baseline_mse"] / sel["rungs"]["fitted"]["baseline_mse"] - 1) < 1e-6]
    if len(tied) == 3:
        L.append(r"\\[2pt]\footnotesize AR, DLinear and the tuned ridge agree with the primary "
                 "denominator to eight significant figures, which is not a coincidence and not an "
                 "error: M4-Monthly is univariate, so all four reduce to the same least-squares map "
                 r"$\mathbb{R}^{96}\!\to\!\mathbb{R}^{18}$.")
    L.append(r"\end{center}")
    return L


def runs_table(runs, reg, missing):
    seeds = reg["runs"]["seeds"]
    L = ["% GENERATED by scripts/emit_chronos_m4.py -- do not edit by hand.",
         r"\begin{center}", r"\small", r"\setlength{\tabcolsep}{5pt}",
         r"\begin{tabular}{@{}lcccccc@{}}", r"\toprule",
         r"& \multicolumn{2}{c}{Held-out forgetting} & & "
         r"\multicolumn{2}{c}{CKA / encoder $\ell_2$} & \\",
         r"\cmidrule(lr){2-3}\cmidrule(lr){5-6}",
         r"Seed & B (full FT) & D (frozen enc.) & $\Delta_{\text{enc}}$ & B & D & "
         r"Best epoch B / D \\", r"\midrule"]
    d_enc = []
    for seed in seeds:
        b, d = runs.get(("B", seed)), runs.get(("D", seed))
        if b is None or d is None:
            L.append(f"{seed} & \\multicolumn{{6}}{{c}}{{\\textit{{run missing}}}} \\\\")
            continue
        delta = b["forgetting_pct"] - d["forgetting_pct"]
        d_enc.append(delta)
        L.append(f"{seed} & ${b['forgetting_pct']:+.2f}\\%$ & ${d['forgetting_pct']:+.2f}\\%$ & "
                 f"${delta:+.2f}$ & ${b['final_cka']:.4f}$\\,/\\,${b['weight_drift']:.1f}$ & "
                 f"${d['final_cka']:.4f}$\\,/\\,${d['weight_drift']:.1f}$ & "
                 f"{b['best_epoch']} / {d['best_epoch']} \\\\")
    stat = summarise(d_enc)
    if stat:
        L += [r"\midrule",
              f"mean & ${np.mean([runs[('B', s)]['forgetting_pct'] for s in seeds if ('B', s) in runs]):+.2f}\\%$ & "
              f"${np.mean([runs[('D', s)]['forgetting_pct'] for s in seeds if ('D', s) in runs]):+.2f}\\%$ & "
              f"${stat['mean']:+.2f} \\pm {stat['sem']:.2f}$ & "
              r"\multicolumn{3}{l}{"
              f"95\\% CI ${stat['lo']:+.2f}$ to ${stat['hi']:+.2f}$, {stat['call']}" + r"} \\"]
    L += [r"\bottomrule", r"\end{tabular}"]
    if missing:
        L.append(r"\\[2pt]\textbf{PROVISIONAL:} " +
                 f"{len(missing)} of {2 * len(seeds)} registered runs are missing "
                 f"({', '.join(f'{c}/{s}' for c, s in missing)}).")
    L.append(r"\end{center}")
    return L


def summarise(d):
    """Paired summary over seeds: SEM, std at both ddofs, the t-interval, the MDE, the three-way call.

    All three dispersions are computed because this repo's conventions are mixed -- SEM in the body,
    std in two tables, ddof=0 in some stored JSON -- and a plus-or-minus whose convention is guessed
    is a number that will be wrong in one of the three places.
    """
    if len(d) < 2:
        return None
    d = np.asarray(d, dtype=float)
    n = len(d)
    mean, sd1, sd0 = float(d.mean()), float(d.std(ddof=1)), float(d.std(ddof=0))
    sem = sd1 / np.sqrt(n)
    tcrit = float(stats.t.ppf(0.975, n - 1))
    lo, hi = mean - tcrit * sem, mean + tcrit * sem
    t, p = stats.ttest_1samp(d, 0.0)
    call = ("freezing decisively better" if lo > 0 else
            "adaptation decisively better" if hi < 0 else "inconclusive")
    return dict(n=n, mean=mean, sd_ddof1=sd1, sd_ddof0=sd0, sem=float(sem),
                lo=float(lo), hi=float(hi), t=float(t), p=float(p),
                mde=float(tcrit * sem), call=call)


def main():
    gate, reg, runs, missing = load()
    sel = gate["splits"]["selection"]

    OUT_GATE.write_text("\n".join(gate_table(gate)) + "\n")
    OUT_RUNS.write_text("\n".join(runs_table(runs, reg, missing)) + "\n")
    print(f"wrote {OUT_GATE.relative_to(ROOT)}")
    print(f"wrote {OUT_RUNS.relative_to(ROOT)}")

    # --- everything the appendix prose is allowed to say, printed so it can be copied rather than
    # recalled. Nothing here is rounded differently from the tables above.
    print(f"\ngate, selection split (PRIMARY): zs {sel['zs_mse']:.4f}  "
          f"fitted {sel['rungs']['fitted']['baseline_mse']:.4f}  "
          f"V_ridge {sel['primary_r2_task']:+.4f}  "
          f"{'PASS' if sel['primary_passes'] else 'FAIL'} at {gate['threshold']}")
    print(f"  constant floor {sel['constant_floor_mse']:.4f};  inadmissible rungs: "
          f"{', '.join(sel['inadmissible_rungs']) or 'none'}")
    print(f"  trend (superseded) would have read {sel['rungs']['trend']['r2_task']:+.4f}")
    print(f"  best admissible rung {sel['best_admissible_rung']}  "
          f"({sel['rungs'][sel['best_admissible_rung']]['r2_task']:+.4f}); "
          f"worst case {sel['worst_case_r2_task']:+.4f}; "
          f"survives every admissible rung: {sel['survives_every_admissible_rung']}")
    ho = gate["splits"]["heldout"]
    print(f"  held-out (secondary): V_ridge {ho['primary_r2_task']:+.4f}, "
          f"survives every admissible rung: {ho['survives_every_admissible_rung']}")

    if missing:
        print(f"\nPROVISIONAL: missing {missing}")
    if not runs:
        return 0

    for cond in reg["runs"]["conditions"]:
        rs = [runs[(cond, s)] for s in reg["runs"]["seeds"] if (cond, s) in runs]
        f = [r["forgetting_pct"] for r in rs]
        print(f"\ncondition {cond}: n={len(rs)}  forgetting mean {np.mean(f):+.2f}%  "
              f"sd(ddof=1) {np.std(f, ddof=1) if len(f) > 1 else float('nan'):.2f}  "
              f"range {min(f):+.2f}..{max(f):+.2f}")
        print(f"  CKA {[round(r['final_cka'], 4) for r in rs]}  "
              f"encoder l2 {[round(r['weight_drift'], 1) for r in rs]}  "
              f"best epochs {[r['best_epoch'] for r in rs]} "
              f"(stopped {[r['stopped_epoch'] for r in rs]})")
        print(f"  per-seed gate {[round(r['gate_r2_task'], 4) for r in rs]}  "
              f"(the standalone gate is {sel['primary_r2_task']:+.4f}; Chronos samples, so these "
              f"differ by sampling noise, not by estimator)")
        if cond == "D":
            # Not a measurement: condition D freezes t5.encoder.parameters(), which on Chronos
            # includes the shared token embedding, so the encoder's output is identical by
            # construction. Asserted so that a future change to what D freezes cannot pass silently.
            # The tolerance is 1e-6 rather than equality because CKA of a representation with itself
            # comes out as 1 - 4e-8 in float64 (a ratio of Frobenius norms, not a comparison), and an
            # exact-equality assert would fail on arithmetic rather than on a protocol change. The
            # zero drift below is the exact check: a frozen encoder's weights are bitwise unchanged.
            assert all(abs(r["final_cka"] - 1.0) < 1e-6 for r in rs), (
                f"condition D CKA should be 1 by construction, got "
                f"{[r['final_cka'] for r in rs]}")
            assert all(r["weight_drift"] == 0.0 for r in rs), "frozen encoder drifted"

    stat = summarise([runs[("B", s)]["forgetting_pct"] - runs[("D", s)]["forgetting_pct"]
                      for s in reg["runs"]["seeds"] if ("B", s) in runs and ("D", s) in runs])
    if stat:
        print(f"\nDelta_enc = forgetting_B - forgetting_D, paired over {stat['n']} seeds")
        print(f"  mean {stat['mean']:+.2f}  sem {stat['sem']:.2f}  "
              f"sd(ddof=1) {stat['sd_ddof1']:.2f}  sd(ddof=0) {stat['sd_ddof0']:.2f}")
        print(f"  95% CI [{stat['lo']:+.2f}, {stat['hi']:+.2f}]  t {stat['t']:+.3f}  "
              f"p {stat['p']:.3f}  MDE {stat['mde']:.2f} pp")
        print(f"  CALL: {stat['call']}  (unadjusted; this cell is NOT in the 31-cell BH family)")
        # The degradation definition, all three clauses, on this cell's own numbers.
        fb = np.mean([runs[("B", s)]["forgetting_pct"] for s in reg["runs"]["seeds"]
                      if ("B", s) in runs])
        fd = np.mean([runs[("D", s)]["forgetting_pct"] for s in reg["runs"]["seeds"]
                      if ("D", s) in runs])
        clauses = dict(gate_passes=bool(sel["primary_passes"]), forg_B_positive=bool(fb > 0),
                       forg_D_negative=bool(fd < 0))
        print(f"  degradation clauses: {clauses} -> "
              f"{'DEGRADATION CELL' if all(clauses.values()) else 'not a degradation cell'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
