#!/usr/bin/env python3
"""
Emit the cross-backbone table: every non-Moirai cell, with the SELECTION-SPLIT
gate, CKA, and the two outcome readings (full fine-tune and frozen encoder, each
as % change against zero-shot; negative = better than zero-shot).

Reads only cell_matrix.build_rows(), which is itself sourced from committed run
JSON plus results/gate_{GATE_SPLIT}_side.json -- gate_val_side.json as of
20 Sep 2026, not the test-side file this docstring named until then. The gate
column is therefore scored on windows DISJOINT from the outcome columns beside
it, which is the whole point of the split and was mis-stated in this table's
caption. No model calls, nothing typed by hand.
Regenerate with:  python3 scripts/emit_crossbackbone.py
"""
import contextlib
import io
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
import cell_matrix  # noqa: E402

OUT = ROOT / "paper_8/tables/crossbackbone.tex"
GATE = 0.20

# cell key -> (backbone, dataset) for the non-Moirai arms
NON_MOIRAI = {
    "chronos_ettm2":       ("Chronos-T5-S", "ETTm2"),
    "chronos_etth2":       ("Chronos-T5-S", "ETTh2"),
    "chronos_weather":     ("Chronos-T5-S", "Weather"),
    "chronos_etth1":       ("Chronos-T5-S", "ETTh1"),
    "chronos_electricity": ("Chronos-T5-S", "Electricity"),
    "timesfm_ettm2":       ("TimesFM-2.5",  "ETTm2"),
    "timesfm_etth2":       ("TimesFM-2.5",  "ETTh2"),
    "timesfm_weather":     ("TimesFM-2.5",  "Weather"),
    "timesfm_etth1":       ("TimesFM-2.5",  "ETTh1"),
}


def main():
    with contextlib.redirect_stdout(io.StringIO()):
        rows = {r["ref"]: r for r in cell_matrix.build_rows()}

    picked = []
    for key, (bk, ds) in NON_MOIRAI.items():
        r = rows.get(key)
        if r is None:
            print(f"  MISSING {key}", file=sys.stderr)
            continue
        picked.append((bk, ds, r))
    picked.sort(key=lambda x: (x[0], x[2]["forg_b"]))

    L = ["% GENERATED by scripts/emit_crossbackbone.py -- do not edit by hand.",
         r"\begin{center}", r"\small", r"\setlength{\tabcolsep}{5pt}",
         r"\begin{tabular}{@{}llcccc@{}}", r"\toprule",
         r"Backbone & Dataset & Gate $\Vb{\text{ridge}}$ & CKA & Full FT & Frozen \\",
         r"\midrule"]
    prev = None
    for bk, ds, r in picked:
        if prev is not None and bk != prev:
            L.append(r"\midrule")
        prev = bk
        gate = r["gate"]
        gs = f"${gate:+.3f}$" + ("" if gate >= GATE else r"\,\textsuperscript{f}")
        L.append(f"{bk} & {ds} & {gs} & ${r['cka']:.3f}$ & "
                 f"${r['forg_b']:+.1f}\\%$ & ${r['forg_d']:+.1f}\\%$ \\\\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{center}"]
    OUT.write_text("\n".join(L) + "\n")

    print(f"wrote {OUT.relative_to(ROOT)}")

    # Since the gate was corrected to the fitted linear baseline (see the paper's gate-correction
    # appendix) NO non-Moirai cell gate-passes, so every "gate-passing ..." range below is over an
    # empty list. Report the full set as well, and never call min()/max() on an empty selection --
    # an earlier version crashed here, after writing the table, once `passing` went to zero.
    def _range(label, rows):
        if not rows:
            print(f"  {label}: none")
            return
        fb = [r["forg_b"] for r in rows]
        ck = [r["cka"] for r in rows]
        print(f"  {label}: n={len(rows)}  forg_B {min(fb):+.1f}%..{max(fb):+.1f}%  "
              f"CKA {min(ck):.3f}..{max(ck):.3f}")

    passing = [(bk, ds, r) for bk, ds, r in picked if r["gate"] >= GATE]
    print(f"non-Moirai cells: {len(picked)}   gate-passing: {len(passing)}")
    _range("all non-Moirai cells", [r for _, _, r in picked])
    _range("gate-passing", [r for _, _, r in passing])
    for bk_name in ("Chronos", "TimesFM"):
        _range(f"{bk_name} (all)", [r for bk, _, r in picked if bk.startswith(bk_name)])
        _range(f"{bk_name} (gate-passing)",
               [r for bk, _, r in passing if bk.startswith(bk_name)])


if __name__ == "__main__":
    main()
