#!/usr/bin/env python3
"""
Emit the within-backbone dissociation table: every Moirai-Base cell, ordered by
CKA, with the two outcome readings (full fine-tune and frozen encoder, each as %
change against zero-shot; negative = better than zero-shot) and the manipulated
contrast between them.

WHY THIS TABLE EXISTS. The sharpest form of this paper's dissociation finding
lived only in body prose (Exp. 3): "within Moirai-Base the two least drifted
cells are the only two that degrade, while its two most drifted improve the most
in the arm". Four CKA values and four outcome percentages, hand-typed, in no
table and checked by nobody -- which is how every hand-typed number in this
project has gone stale. The prose is now checked against this file and this file
against the run records.

Reads only cell_matrix.build_rows(), sourced from committed run JSON plus
results/gate_test_side.json. No model calls. Regenerate with:
    python3 scripts/emit_dissociation.py

The script ASSERTS the qualitative claim the prose makes -- that the two
highest-CKA cells in the arm are exactly the two with positive condition-B
forgetting -- and exits non-zero if the records ever stop supporting it. A table
that can still be emitted after its own claim dies is not a check.
"""
import contextlib
import io
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
import cell_matrix  # noqa: E402

OUT = ROOT / "paper_8/tables/dissociation.tex"
ARM = "base_"          # Moirai-Base; small_/large_ are the other two capacities
GATE = 0.20

# ref -> printed dataset label. Built from the ref rather than r["cell"], whose
# two formats ("Moirai-base/ETTh2 h192 n1000" and "Moirai-base_ETTh1_h192")
# differ by which pipeline wrote the cell.
def label(ref):
    _, ds, h = ref.split("_", 2)
    return ds, h.lstrip("h")


def main():
    with contextlib.redirect_stdout(io.StringIO()):
        rows = [r for r in cell_matrix.build_rows()
                if r["ref"].startswith(ARM) and r.get("cka") is not None]

    if not rows:
        print("no Moirai-Base cells with CKA found", file=sys.stderr)
        return 1
    rows.sort(key=lambda r: r["cka"])          # most drifted first

    L = ["% GENERATED by scripts/emit_dissociation.py -- do not edit by hand.",
         "% Moirai-Base, ordered by CKA (most drifted first). Full FT and Frozen are",
         "% percent change in held-out MSE against zero-shot; negative is better.",
         r"\begin{center}", r"\small", r"\setlength{\tabcolsep}{5pt}",
         r"\begin{tabular}{@{}lccccc@{}}", r"\toprule",
         r"Cell ($h$) & CKA & Gate & Full FT & Frozen & $\denc$ \\",
         r"\midrule"]
    for r in rows:
        ds, h = label(r["ref"])
        gate = r["gate"]
        gs = f"${gate:+.3f}$" + ("" if gate >= GATE else r"\,\textsuperscript{f}")
        L.append(f"{ds} ({h}) & ${r['cka']:.3f}$ & {gs} & "
                 f"${r['forg_b']:+.1f}\\%$ & ${r['forg_d']:+.1f}\\%$ & "
                 f"${r['bd_test']:+.1f}$ \\\\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{center}"]
    OUT.write_text("\n".join(L) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}  ({len(rows)} cells)")

    # -- the assertion. Two highest-CKA cells == the two with forg_B > 0.
    by_cka = sorted(rows, key=lambda r: r["cka"])
    least_drifted = {r["ref"] for r in by_cka[-2:]}
    degrading = {r["ref"] for r in rows if r["forg_b"] > 0}
    most_improved = {r["ref"] for r in sorted(rows, key=lambda r: r["forg_b"])[:2]}
    most_drifted = {r["ref"] for r in by_cka[:2]}

    ok = True
    if least_drifted != degrading:
        print(f"  CLAIM FAILED: least-drifted {sorted(least_drifted)} != "
              f"degrading {sorted(degrading)}", file=sys.stderr)
        ok = False
    if most_drifted != most_improved:
        print(f"  CLAIM FAILED: most-drifted {sorted(most_drifted)} != "
              f"most-improved {sorted(most_improved)}", file=sys.stderr)
        ok = False
    for r in by_cka[-2:]:
        ds, h = label(r["ref"])
        print(f"  least drifted: {ds} h{h}  CKA {r['cka']:.3f}  "
              f"forg_B {r['forg_b']:+.1f}%")
    for r in by_cka[:2]:
        ds, h = label(r["ref"])
        print(f"  most drifted:  {ds} h{h}  CKA {r['cka']:.3f}  "
              f"forg_B {r['forg_b']:+.1f}%")
    print("  claim holds" if ok else "  CLAIM DOES NOT HOLD")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
