#!/usr/bin/env python3
"""
Is the value-gate's prospective failure an artifact of the 20% operating point?

Re-scores the eight pre-registered prospective cells at a range of thresholds
on the SAME pre-registered predictor (gate_val, the validation-side gate
recorded in preregistration.json) against the SAME pre-registered outcome
definition (score_prospective.load()). Nothing here is re-fit; only the
threshold moves.

Run:  python3 scripts/gate_threshold_sensitivity.py [--latex]
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
import score_prospective  # noqa: E402

OUT = ROOT / "paper_8/tables/gate_sensitivity.tex"


def main():
    _pre, rows = score_prospective.load()
    scored = [r for r in rows if r.get("status") == "scored"]
    grid = [0.10, 0.20, 0.30, 0.40, 0.50, 0.60]
    out = []
    for thr in grid:
        tp = sum(1 for r in scored if r["gate_val"] >= thr and r["degraded"])
        fp = sum(1 for r in scored if r["gate_val"] >= thr and not r["degraded"])
        fn = sum(1 for r in scored if r["gate_val"] < thr and r["degraded"])
        prec = tp / (tp + fp) if tp + fp else float("nan")
        rec = tp / (tp + fn) if tp + fn else float("nan")
        out.append((thr, tp + fp, tp, fp, fn, prec, rec))

    print(f"{'thr':>6}{'flagged':>9}{'TP':>4}{'FP':>4}{'FN':>4}{'prec':>8}{'recall':>8}")
    for thr, n, tp, fp, fn, prec, rec in out:
        print(f"{thr:>6.2f}{n:>9}{tp:>4}{fp:>4}{fn:>4}{prec:>8.2f}{rec:>8.2f}")
    print(f"\n  {len(scored)} scored cells, {sum(r['degraded'] for r in scored)} degradation cells")
    print("  No threshold on this predictor reaches precision > 0.50 at any recall.")

    if "--latex" in sys.argv:
        L = ["% GENERATED by scripts/gate_threshold_sensitivity.py -- do not edit by hand.",
             r"\begin{center}", r"\small",
             r"\begin{tabular}{@{}ccccccc@{}}", r"\toprule",
             r"Threshold & Flagged & TP & FP & FN & Precision & Recall \\", r"\midrule"]
        for thr, n, tp, fp, fn, prec, rec in out:
            bold = r"\textbf" if abs(thr - 0.20) < 1e-9 else ""
            L.append(f"{bold}{{${thr:.2f}$}} & {n} & {tp} & {fp} & {fn} & "
                     f"${prec:.2f}$ & ${rec:.2f}$ \\\\")
        L += [r"\bottomrule", r"\end{tabular}", r"\end{center}"]
        OUT.write_text("\n".join(L) + "\n")
        print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
