#!/usr/bin/env python3
"""
Score the pre-registered predictions against what the prospective cells actually did.

The predictions were frozen in results/v47_prospective/preregistration.json and committed to git
BEFORE any condition B or D run existed (commit 69d3379). This script only reads that file and the
finished runs; it decides nothing.

Two rules were registered:
  gate rule     gate_val >= 0.20 -> at risk of degradation.  The paper's own criterion.
  dataset rule  dataset in {ETTh1, Weather} -> degradation.  POST HOC pattern from the published
                cells, registered as a competitor so the gate's performance has a reference point.

Outcome is degradation_cells()' definition applied unchanged: gate-passing AND forg_B > 0 in every
seed AND forg_D < 0 in every seed. Cells with fewer than cell_matrix.MIN_SEEDS seeds are still
running and are reported as pending, never scored -- a one-seed cell passes the "every seed" clause
trivially.

Run:  python3 scripts/score_prospective.py
      python3 scripts/score_prospective.py --latex
"""
import argparse
import contextlib
import io
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
import cell_matrix  # noqa: E402

PRE = ROOT / "results/v47_prospective/preregistration.json"


def load():
    pre = json.loads(PRE.read_text())
    with contextlib.redirect_stdout(io.StringIO()):
        rows = {r["ref"]: r for r in cell_matrix.build_rows()}
    gates = {k: v["r2_task"] for k, v in
             json.loads((ROOT / "results/gate_test_side.json").read_text()).items()}
    out = []
    for c in pre["cells"]:
        r = rows.get(c["cell"])
        if r is None or r.get("forg_b") is None:
            out.append(dict(c, status="pending")); continue
        deg = (gates.get(c["cell"], -1) >= pre["gate_threshold"]
               and r["forg_b"] > 0 and r["forg_d"] < 0
               and r["forg_b_pos"] == r["seeds"] and r["forg_d_neg"] == r["seeds"])
        sem = (r["bd_test_sd"] or 0) / max(r["seeds"], 1) ** 0.5
        reading = ("directional" if abs(r["bd_test"]) < 2 * sem
                   else ("freezing better" if r["bd_test"] > 0 else "adaptation helps"))
        out.append(dict(c, status="scored", degraded=deg, reading=reading, sem=sem,
                        gate_test=gates.get(c["cell"]), seeds=r["seeds"],
                        forg_b=r["forg_b"], forg_b_pos=r["forg_b_pos"],
                        forg_d=r["forg_d"], bd_test=r["bd_test"]))
    return pre, out


def main():
    ap = argparse.ArgumentParser(); ap.add_argument("--latex", action="store_true")
    a = ap.parse_args()
    pre, cells = load()
    done = [c for c in cells if c["status"] == "scored"]

    print("=" * 100)
    print("PROSPECTIVE TEST -- predictions frozen in git before any B/D run existed")
    print(f"registered {pre['written_utc']} at {pre['git_head'][:12]}")
    print("=" * 100)
    hdr = f"{'cell':24s} {'gate_val':>8s} {'gate':>7s} {'forg_B':>14s} {'B-D':>15s} {'degraded':>9s}"
    print(hdr + "  gate  data")
    for c in cells:
        if c["status"] == "pending":
            print(f"{c['cell']:24s} {c['gate_val']:+8.3f}   ...still running"); continue
        print(f"{c['cell']:24s} {c['gate_val']:+8.3f} {c['gate_test']:+7.3f} "
              f"{c['forg_b']:+7.2f}({c['forg_b_pos']}/{c['seeds']}) "
              f"{c['bd_test']:+7.2f}±{c['sem']:5.2f} {'YES' if c['degraded'] else 'no':>9s}  "
              f"{'OK' if c['predict_gate_rule'] == c['degraded'] else ' X':>4s}"
              f"{'OK' if c['predict_dataset_rule'] == c['degraded'] else ' X':>6s}")

    ng = sum(c["predict_gate_rule"] == c["degraded"] for c in done)
    nd = sum(c["predict_dataset_rule"] == c["degraded"] for c in done)
    ndeg = sum(c["degraded"] for c in done)
    print(f"\n  scored {len(done)}/{len(cells)}   degradation cells among them: {ndeg}")
    print(f"  gate rule    {ng}/{len(done)} correct")
    print(f"  dataset rule {nd}/{len(done)} correct")
    # the gate fires on everything, so state its confusion matrix rather than just accuracy
    tp = sum(c["predict_gate_rule"] and c["degraded"] for c in done)
    fp = sum(c["predict_gate_rule"] and not c["degraded"] for c in done)
    fn = sum((not c["predict_gate_rule"]) and c["degraded"] for c in done)
    print(f"  gate rule confusion: TP {tp}  FP {fp}  FN {fn}  "
          f"(precision {tp/(tp+fp):.2f} at recall {tp/(tp+fn) if tp+fn else float('nan'):.2f})")

    if a.latex:
        out = ROOT / "paper_8/tables/prospective.tex"
        L = ["% GENERATED by scripts/score_prospective.py --latex -- do not edit by hand.",
             r"\begin{center}", r"\footnotesize", r"\setlength{\tabcolsep}{4pt}",
             r"\begin{tabular}{@{}lccccc@{}}", r"\toprule",
             r"Cell (new) & gate$_\text{val}$ & forg$_\text{B}$ & B$-$D held-out & Degradation? "
             r"& Predicted \\", r"\midrule"]
        for c in done:
            pg = "gate\\,$\\times$" if c["predict_gate_rule"] != c["degraded"] else "gate\\,$\\checkmark$"
            pd_ = "data\\,$\\times$" if c["predict_dataset_rule"] != c["degraded"] else "data\\,$\\checkmark$"
            name = c["cell"].replace("_", " ").replace("h96", "($h{=}96$)").replace("h192", "($h{=}192$)")
            L.append(f"{name} & ${c['gate_val']:+.2f}$ & ${c['forg_b']:+.1f}$ "
                     f"({c['forg_b_pos']}/{c['seeds']}) & ${c['bd_test']:+.1f}{{\\pm}}{c['sem']:.1f}$ & "
                     f"{'\\textbf{yes}' if c['degraded'] else 'no'} & {pg}, {pd_} \\\\")
        L += [r"\bottomrule", r"\end{tabular}", r"\end{center}", ""]
        out.write_text("\n".join(L))
        print(f"\nwrote {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
